services:
  - type: web_service
    name: personal-task-manager-backend
    env: node
    branch: main
    root: server
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        value: https://personal-task-manager-frontend.onrender.com
      - key: HOST
        value: 0.0.0.0

  - type: static_site
    name: personal-task-manager-frontend
    env: static
    branch: main
    root: client
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://personal-task-manager-backend.onrender.com/api
